"""create 2 first tables

Revision ID: 0d4dea0c7947
Revises: 
Create Date: 2026-06-23 14:29:21.584355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4dea0c7947'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desks_description'), 'desks', ['description'], unique=False)
    op.create_index(op.f('ix_desks_id'), 'desks', ['id'], unique=False)
    op.create_index(op.f('ix_desks_title'), 'desks', ['title'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kanji', sa.String(length=255), nullable=True),
    sa.Column('yomikata', sa.String(length=255), nullable=True),
    sa.Column('meaning', sa.String(length=255), nullable=True),
    sa.Column('jlpt_level', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_jlpt_level'), 'words', ['jlpt_level'], unique=False)
    op.create_index(op.f('ix_words_kanji'), 'words', ['kanji'], unique=False)
    op.create_index(op.f('ix_words_meaning'), 'words', ['meaning'], unique=False)
    op.create_index(op.f('ix_words_yomikata'), 'words', ['yomikata'], unique=False)
    op.create_table('deck_words',
    sa.Column('desk_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['desk_id'], ['desks.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('desk_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_words')
    op.drop_index(op.f('ix_words_yomikata'), table_name='words')
    op.drop_index(op.f('ix_words_meaning'), table_name='words')
    op.drop_index(op.f('ix_words_kanji'), table_name='words')
    op.drop_index(op.f('ix_words_jlpt_level'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_desks_title'), table_name='desks')
    op.drop_index(op.f('ix_desks_id'), table_name='desks')
    op.drop_index(op.f('ix_desks_description'), table_name='desks')
    op.drop_table('desks')
    # ### end Alembic commands ###
