"""change 2 first tables

Revision ID: 717e27940ff1
Revises: 0d4dea0c7947
Create Date: 2026-06-24 08:51:32.174814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717e27940ff1'
down_revision: Union[str, Sequence[str], None] = '0d4dea0c7947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('desks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('desks', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('words', 'yomikata',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('words', 'meaning',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('words', 'jlpt_level',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'jlpt_level',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('words', 'meaning',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('words', 'yomikata',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('desks', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('desks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
