"""update ID comlumns

Revision ID: 8c2367544f74
Revises: ed63ea29378a
Create Date: 2026-06-24 14:12:20.187770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2367544f74'
down_revision: Union[str, Sequence[str], None] = 'ed63ea29378a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desks_description'), table_name='desks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_desks_description'), 'desks', ['description'], unique=False)
    # ### end Alembic commands ###
