"""rename desk to deck and setup async

Revision ID: 859758c38c3f
Revises: 2b99a0aef0e7
Create Date: 2026-06-29 21:53:32.355378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859758c38c3f'
down_revision: Union[str, Sequence[str], None] = '2b99a0aef0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('desks', 'decks')
    op.add_column('deck_words', sa.Column('deck_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('deck_words_desk_id_fkey'), 'deck_words', type_='foreignkey')
    op.create_foreign_key(None, 'deck_words', 'decks', ['deck_id'], ['id'])
    op.drop_column('deck_words', 'desk_id')
    op.drop_index(op.f('ix_desks_id'), table_name='decks')
    op.drop_index(op.f('ix_desks_title'), table_name='decks')
    op.create_index(op.f('ix_decks_id'), 'decks', ['id'], unique=False)
    op.create_index(op.f('ix_decks_title'), 'decks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decks_title'), table_name='decks')
    op.drop_index(op.f('ix_decks_id'), table_name='decks')
    op.create_index(op.f('ix_desks_title'), 'decks', ['title'], unique=False)
    op.create_index(op.f('ix_desks_id'), 'decks', ['id'], unique=False)
    op.add_column('deck_words', sa.Column('desk_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deck_words', type_='foreignkey')
    op.create_foreign_key(op.f('deck_words_desk_id_fkey'), 'deck_words', 'decks', ['desk_id'], ['id'])
    op.drop_column('deck_words', 'deck_id')
    # ### end Alembic commands ###
