"""add supervisor to user

Revision ID: d837de259ab9
Revises: cc920eb33257
Create Date: 2026-06-30 08:16:07.026758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd837de259ab9'
down_revision: Union[str, Sequence[str], None] = 'cc920eb33257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_supervisor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_supervisor')
    # ### end Alembic commands ###
